### ISSUE TITLE
DL24 - incorrect readings

### ISSUE THREAD

**Issue by danielskowronski** [lanrat/usb-meter#1]
On DL24 it shows incorrect readings - voltage is 10 times smaller and current is 10 times larger, and other ones seem off on initial look. 

![Screenshot 2023-01-17 at 16 06 45](https://user-images.githubusercontent.com/8194525/212934475-3d585eb3-6689-4057-8804-94986cece642.png)

I'll dig into details later and probably provide PR with patch :)

**Comment by lanrat** [comment]
Thanks for the bug report!

I don't have a DL24 to test with, but I would happily accept a PR if you can detect the model and adjust the values accordingly.

**Comment by danielskowronski** [comment]
There seem to be some alternative protocols for DL24 which would explain incorrect mappings between data I'm receiving and https://github.com/syssi/esphome-atorch-dl24/blob/main/components/atorch_dl24/button/__init__.py#L12

If I fail to find a way to convince my device to switch protocols (which may be tricky as even the official *E_Test* app uses that protocol and has many fields missing and some with very low resolution) I'll submit PR with a bunch of `if (this.type == DEVICE_TYPE.DC)` and probably some code for UI part to hide fields not related to DC meter.

**Comment by danielskowronski** [comment]
I think I know what's going on - DL24 can use both ATorch protocol in DC mode (default one used by E-Test app and having severe limitations like capacity returned with resolution of 10 mAh) and PX100 protocol.

ATorch protocol for DC meter is described in https://github.com/syssi/esphome-atorch-dl24/blob/main/docs/protocol-design.md#dc-meter-report with single addition of Uint24 at 0x10 that represents capacity in tens of mAh.

PX100 implemented for example in https://github.com/KrystianD/dl24-electronic-load works over Bluetooth and USB serial ports and returns data as expected, for example:

```
dl24-manage -p /dev/tty.E-testSPP read

             enabled:      yes    
             voltage:    5.206 V  
             current:    0.302 A  
              energy:      1.8 Wh 
              charge:    0.109 Ah 
                time:  0:09:41    
         temperature:       25 °C 
       current_limit:      0.3 A  
      voltage_cutoff:      4.5 V  
               timer:  5:37:00    
```

More details are on EEVblog forum thread https://www.eevblog.com/forum/testgear/atorch-dl24-electronic-load-software/msg3219530/#msg3219530

I'll prepare MR for ATorch DC mode soon. @lanrat would you like to have this project extended for that PX100 mode or do you think that this kind of meter (in fact it's electronic load with meter) is too different from the original project purpose?

**Comment by lanrat** [comment]
Fixed in #2

**Comment by lanrat** [comment]
> I'll prepare MR for ATorch DC mode soon. @lanrat would you like to have this project extended for that PX100 mode or do you think that this kind of meter (in fact it's electronic load with meter) is too different from the original project purpose?

If you would like to add support for PX100 mode I would accept a PR, however I would be unable to test it as I do not own such a device.

**Comment by danielskowronski** [comment]
> If you would like to add support for PX100 mode I would accept a PR, however I would be unable to test it as I do not own such a device.

Great, I'll try to figure out how to do it then and raise another PR :)
