### ISSUE TITLE
what is node.js npm used for here? 

### ISSUE THREAD

**Issue by selevo** [lanrat/usb-meter#4]
what is node.js npm used for here? 
Is this some kind of scalable server application? 
Why can’t it be as simple as possible to make three files:
index.html 
ble.js 
page.css
 without any interpreter installations, connection deployment builds and adventures? 
That is, it is as simple as possible to start. How much information do I need to read, spend hours to make modifications or even run it for myself? Once again I can’t understand why all this redundancy and antics? It just turns most people off. Then what is this project for? so that someone out of one thousand would be interested? In general, there are a lot of questions...

**Comment by lanrat** [comment]
This is a typescript application, its needs typescript to compile it.
NPM manages the external libraries.
No modifications are needed.

The readme outlines how to build it.
https://github.com/lanrat/usb-meter?tab=readme-ov-file#building

**Comment by selevo** [comment]
:)
I understand what it is, in general terms.
I asked something else, why all this car production workshop for a one-page site, when there are only a few ready-made files that I mentioned. And which you just need to run in a browser in the https zone or on your server (for the ble API to work).

Why should people install all this rubbish on their computer, build/deploy an application that will make a one-page website....
Why even write like this to turn a non-language into a language that the browser can understand?

And all this junk of the modern frontend is absolutely unnecessary for us, ordinary people.
Why do we need this headache?

We need three files and copy-paste.
Instead of npm install
npm run build

**Comment by lanrat** [comment]
If you don't like the code that I provide here free of charge, then you are free to not use it.
